// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/gilabs/gims/api/internal/organization/domain/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/gilabs/gims/api/internal/organization/data/models"
)

// JobPositionRepository is an autogenerated mock type for the JobPositionRepository type
type JobPositionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, j
func (_m *JobPositionRepository) Create(ctx context.Context, j *models.JobPosition) error {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.JobPosition) error); ok {
		r0 = rf(ctx, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *JobPositionRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *JobPositionRepository) FindByID(ctx context.Context, id string) (*models.JobPosition, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.JobPosition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.JobPosition, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.JobPosition); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobPosition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *JobPositionRepository) FindByName(ctx context.Context, name string) (*models.JobPosition, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.JobPosition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.JobPosition, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.JobPosition); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobPosition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, req
func (_m *JobPositionRepository) List(ctx context.Context, req *dto.ListJobPositionsRequest) ([]models.JobPosition, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.JobPosition
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListJobPositionsRequest) ([]models.JobPosition, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListJobPositionsRequest) []models.JobPosition); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobPosition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ListJobPositionsRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dto.ListJobPositionsRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, j
func (_m *JobPositionRepository) Update(ctx context.Context, j *models.JobPosition) error {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.JobPosition) error); ok {
		r0 = rf(ctx, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJobPositionRepository creates a new instance of JobPositionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobPositionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobPositionRepository {
	mock := &JobPositionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
