// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/gilabs/gims/api/internal/permission/domain/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/gilabs/gims/api/internal/permission/data/models"
)

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *PermissionRepository) FindByCode(ctx context.Context, code string) (*models.Permission, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Permission, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Permission); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PermissionRepository) FindByID(ctx context.Context, id string) (*models.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByMenuID provides a mock function with given fields: ctx, menuID
func (_m *PermissionRepository) GetByMenuID(ctx context.Context, menuID string) ([]models.Permission, error) {
	ret := _m.Called(ctx, menuID)

	if len(ret) == 0 {
		panic("no return value specified for GetByMenuID")
	}

	var r0 []models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Permission, error)); ok {
		return rf(ctx, menuID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Permission); ok {
		r0 = rf(ctx, menuID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, menuID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRoleID provides a mock function with given fields: ctx, roleID
func (_m *PermissionRepository) GetByRoleID(ctx context.Context, roleID string) ([]models.Permission, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetByRoleID")
	}

	var r0 []models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Permission, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Permission); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRootMenusWithChildren provides a mock function with given fields: ctx
func (_m *PermissionRepository) GetRootMenusWithChildren(ctx context.Context) ([]models.Menu, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRootMenusWithChildren")
	}

	var r0 []models.Menu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Menu, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Menu); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Menu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPermissions provides a mock function with given fields: ctx, userID
func (_m *PermissionRepository) GetUserPermissions(ctx context.Context, userID string) (*dto.GetUserPermissionsResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 *dto.GetUserPermissionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.GetUserPermissionsResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.GetUserPermissionsResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetUserPermissionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *PermissionRepository) List(ctx context.Context) ([]models.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
