// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/gilabs/gims/api/internal/geographic/domain/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/gilabs/gims/api/internal/geographic/data/models"
)

// CityRepository is an autogenerated mock type for the CityRepository type
type CityRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, c
func (_m *CityRepository) Create(ctx context.Context, c *models.City) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.City) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CityRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *CityRepository) FindByCode(ctx context.Context, code string) (*models.City, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.City, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.City); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *CityRepository) FindByID(ctx context.Context, id string) (*models.City, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.City, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.City); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasDistricts provides a mock function with given fields: ctx, cityID
func (_m *CityRepository) HasDistricts(ctx context.Context, cityID string) (bool, error) {
	ret := _m.Called(ctx, cityID)

	if len(ret) == 0 {
		panic("no return value specified for HasDistricts")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, cityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, cityID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, req
func (_m *CityRepository) List(ctx context.Context, req *dto.ListCitiesRequest) ([]models.City, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.City
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListCitiesRequest) ([]models.City, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListCitiesRequest) []models.City); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ListCitiesRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dto.ListCitiesRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, c
func (_m *CityRepository) Update(ctx context.Context, c *models.City) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.City) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCityRepository creates a new instance of CityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CityRepository {
	mock := &CityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
