package dto

import geographic "github.com/gilabs/gims/api/internal/geographic/domain/dto"

// CreateOutletRequest represents the request to create an outlet.
// Code is auto-generated by the backend (OT-XXXXX format).
type CreateOutletRequest struct {
	Name        string   `json:"name" validate:"required,min=2,max=200"`
	Description string   `json:"description,omitempty"`
	Phone       string   `json:"phone,omitempty"`
	Email       string   `json:"email,omitempty" validate:"omitempty,email"`
	Address     string   `json:"address,omitempty"`
	ProvinceID  *string  `json:"province_id,omitempty"`
	CityID      *string  `json:"city_id,omitempty"`
	DistrictID  *string  `json:"district_id,omitempty"`
	VillageID   *string  `json:"village_id,omitempty"`
	Latitude    *float64 `json:"latitude,omitempty"`
	Longitude   *float64 `json:"longitude,omitempty"`
	ManagerID   *string  `json:"manager_id,omitempty"`
	CompanyID   *string  `json:"company_id,omitempty"`
	IsActive    *bool    `json:"is_active,omitempty"`
	// CreateWarehouse toggles whether a warehouse is automatically created for this outlet
	CreateWarehouse bool `json:"create_warehouse,omitempty"`
}

// UpdateOutletRequest represents the request to update an outlet
type UpdateOutletRequest struct {
	Name        *string  `json:"name,omitempty" validate:"omitempty,min=2,max=200"`
	Description *string  `json:"description,omitempty"`
	Phone       *string  `json:"phone,omitempty"`
	Email       *string  `json:"email,omitempty" validate:"omitempty,email"`
	Address     *string  `json:"address,omitempty"`
	ProvinceID  *string  `json:"province_id,omitempty"`
	CityID      *string  `json:"city_id,omitempty"`
	DistrictID  *string  `json:"district_id,omitempty"`
	VillageID   *string  `json:"village_id,omitempty"`
	Latitude    *float64 `json:"latitude,omitempty"`
	Longitude   *float64 `json:"longitude,omitempty"`
	ManagerID   *string  `json:"manager_id,omitempty"`
	CompanyID   *string  `json:"company_id,omitempty"`
	IsActive    *bool    `json:"is_active,omitempty"`
}

// OutletResponse represents the outlet response DTO
type OutletResponse struct {
	ID          string                       `json:"id"`
	TenantID    string                       `json:"tenant_id,omitempty"`
	Code        string                       `json:"code"`
	Name        string                       `json:"name"`
	Description string                       `json:"description,omitempty"`
	Phone       string                       `json:"phone,omitempty"`
	Email       string                       `json:"email,omitempty"`
	Address     string                       `json:"address,omitempty"`
	ProvinceID  *string                      `json:"province_id,omitempty"`
	Province    *geographic.ProvinceResponse `json:"province,omitempty"`
	CityID      *string                      `json:"city_id,omitempty"`
	City        *geographic.CityResponse     `json:"city,omitempty"`
	DistrictID  *string                      `json:"district_id,omitempty"`
	District    *geographic.DistrictResponse `json:"district,omitempty"`
	VillageID   *string                      `json:"village_id,omitempty"`
	Village     *geographic.VillageResponse  `json:"village,omitempty"`
	Latitude    *float64                     `json:"latitude,omitempty"`
	Longitude   *float64                     `json:"longitude,omitempty"`
	ManagerID   *string                      `json:"manager_id,omitempty"`
	Manager     *ManagerResponse             `json:"manager,omitempty"`
	CompanyID   *string                      `json:"company_id,omitempty"`
	Company     *CompanySimpleResponse       `json:"company,omitempty"`
	WarehouseID *string                      `json:"warehouse_id,omitempty"`
	IsActive    bool                         `json:"is_active"`
	CreatedAt   string                       `json:"created_at"`
	UpdatedAt   string                       `json:"updated_at"`
}

// CompanySimpleResponse is a slim company representation
type CompanySimpleResponse struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// OutletFormDataResponse provides form dropdown options
type OutletFormDataResponse struct {
	Managers  []ManagerResponse       `json:"managers"`
	Companies []CompanySimpleResponse `json:"companies"`
}
