package simulator

import (
	"fmt"
	"net/http"

	"github.com/gilabs/gims/api/analyzer"
)

func (s *SimulationChecker) runPurchaseFlow(cfg *analyzer.Config, runID string) []analyzer.Finding {
	findings := []analyzer.Finding{}
	
	// Pre-condition: find a supplier and a product
	_, getSuppBody, err := s.client.Request(http.MethodGet, "/supplier/suppliers?per_page=1", nil, RoleAdmin)
	if err != nil {
		findings = append(findings, analyzer.Finding{Code: "SIM-P01", Severity: analyzer.SeverityError, Module: "purchase", Message: fmt.Sprintf("Failed to fetch suppliers: %v", err)})
		return findings
	}
	
	suppData, ok := getSuppBody["data"].([]interface{})
	if !ok || len(suppData) == 0 {
		findings = append(findings, analyzer.Finding{Code: "SIM-P01", Severity: analyzer.SeveritySkipped, Module: "purchase", Message: "No supplier found to run purchase E2E flow"})
		return findings
	}
	supplierID := suppData[0].(map[string]interface{})["id"].(string)

	_, getProdBody, err := s.client.Request(http.MethodGet, "/product/products?per_page=1", nil, RoleAdmin)
	if err != nil {
		return findings
	}
	prodData, ok := getProdBody["data"].([]interface{})
	if !ok || len(prodData) == 0 {
		findings = append(findings, analyzer.Finding{Code: "SIM-P01", Severity: analyzer.SeveritySkipped, Module: "purchase", Message: "No products found to run purchase E2E flow"})
		return findings
	}
	productID := prodData[0].(map[string]interface{})["id"].(string)

	// Step 1: Create Purchase Order (add BU for robustness)
	_, getBUBody, _ := s.client.Request(http.MethodGet, "/organization/business-units?per_page=1", nil, RoleAdmin)
	buData, _ := getBUBody["data"].([]interface{})
	businessUnitID := buData[0].(map[string]interface{})["id"].(string)

	poPayload := map[string]interface{}{
		"supplier_id":      supplierID,
		"business_unit_id": businessUnitID,
		"order_date":       "2026-03-24",
		"items": []map[string]interface{}{
			{
				"product_id": productID,
				"quantity":   10,
				"price":      50000,
			},
		},
		"notes": fmt.Sprintf("Auto-generated by QA Simulator %s", runID),
	}
	
	status, body, err := s.client.Request(http.MethodPost, "/purchase/purchase-orders", poPayload, RoleStaff)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P01", 
			Severity: analyzer.SeverityError, 
			Module: "purchase", 
			Message: fmt.Sprintf("Purchase Order Creation Failed: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}
	
	findings = append(findings, analyzer.Finding{
		Code: "SIM-P01", 
		Severity: analyzer.SeverityPass, 
		Module: "purchase", 
		Message: "Purchase Order created successfully via API",
	})
	
	// Extract PO ID and PO Item ID
	poData, ok := body["data"].(map[string]interface{})
	if !ok {
		return findings
	}
	poID := poData["id"].(string)
	var poItemID string
	if items, ok := poData["items"].([]interface{}); ok && len(items) > 0 {
		poItemID = items[0].(map[string]interface{})["id"].(string)
	} else {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P01", Severity: analyzer.SeveritySkipped, Module: "purchase", Message: "PO items not returned in response",
		})
		return findings
	}

	// Step 2: Submit & Approve PO
	s.client.Request(http.MethodPost, fmt.Sprintf("/purchase/purchase-orders/%s/submit", poID), nil, RoleStaff)
	status, body, err = s.client.Request(http.MethodPost, fmt.Sprintf("/purchase/purchase-orders/%s/approve", poID), nil, RoleManager)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P02", 
			Severity: analyzer.SeverityError, 
			Module: "purchase", 
			Message: fmt.Sprintf("Failed to approve PO: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}

	findings = append(findings, analyzer.Finding{
		Code: "SIM-P02", 
		Severity: analyzer.SeverityPass, 
		Module: "purchase", 
		Message: "Purchase Order approved successfully by Manager via API",
	})
	
	// Pre-condition: Find a Warehouse for Goods Receipt
	_, getWhBody, err := s.client.Request(http.MethodGet, "/warehouse/warehouses?per_page=1", nil, RoleAdmin)
	if err != nil {
		return findings
	}
	whData, ok := getWhBody["data"].([]interface{})
	if !ok || len(whData) == 0 {
		return findings // skip GR
	}
	warehouseID := whData[0].(map[string]interface{})["id"].(string)

	// Step 3: Create Goods Receipt (GR)
	grPayload := map[string]interface{}{
		"purchase_order_id": poID,
		"warehouse_id":      warehouseID,
		"notes":             "QA Simulator Receipt",
		"items": []map[string]interface{}{
			{
				"purchase_order_item_id": poItemID,
				"product_id":             productID,
				"quantity_received":      10, // Full receipt
			},
		},
	}
	
	status, body, err = s.client.Request(http.MethodPost, "/purchase/goods-receipt", grPayload, RoleStaff)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P03", 
			Severity: analyzer.SeverityError, 
			Module: "purchase", 
			Message: fmt.Sprintf("Goods Receipt Creation Failed: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}

	findings = append(findings, analyzer.Finding{
		Code: "SIM-P03", 
		Severity: analyzer.SeverityPass, 
		Module: "purchase", 
		Message: "Goods Receipt created successfully via API",
	})
	
	// Extract GR ID
	grData, ok := body["data"].(map[string]interface{})
	if !ok {
		return findings
	}
	grID := grData["id"].(string)

	// Step 4: Submit & Approve GR
	s.client.Request(http.MethodPost, fmt.Sprintf("/purchase/goods-receipt/%s/submit", grID), nil, RoleAdmin)
	status, body, err = s.client.Request(http.MethodPost, fmt.Sprintf("/purchase/goods-receipt/%s/approve", grID), nil, RoleAdmin)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P04", 
			Severity: analyzer.SeverityError, 
			Module: "purchase", 
			Message: fmt.Sprintf("Failed to approve GR: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}
	findings = append(findings, analyzer.Finding{
		Code: "SIM-P04", Severity: analyzer.SeverityPass, Module: "purchase", Message: "Goods Receipt submitted & approved successfully",
	})

	// Step 4.5: Close GR (Required for SI conversion)
	status, body, err = s.client.Request(http.MethodPost, fmt.Sprintf("/purchase/goods-receipt/%s/close", grID), nil, RoleAdmin)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P4.5", Severity: analyzer.SeverityError, Module: "purchase", Message: fmt.Sprintf("Failed to close GR: HTTP %d", status), Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}
	findings = append(findings, analyzer.Finding{Code: "SIM-P4.5", Severity: analyzer.SeverityPass, Module: "purchase", Message: "Goods Receipt closed successfully"})

	// Step 5: Convert GR to Supplier Invoice
	status, body, err = s.client.Request(http.MethodPost, fmt.Sprintf("/purchase/goods-receipt/%s/convert", grID), nil, RoleAdmin)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P05", Severity: analyzer.SeverityError, Module: "purchase", 
			Message: fmt.Sprintf("Failed to convert GR to SI: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}

	siData, ok := body["data"].(map[string]interface{})
	if !ok || siData["supplier_invoice_id"] == nil {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P05", Severity: analyzer.SeverityError, Module: "purchase", 
			Message: "SI conversion response is missing supplier_invoice_id",
		})
		return findings
	}
	siID := siData["supplier_invoice_id"].(string)

	findings = append(findings, analyzer.Finding{
		Code: "SIM-P05", Severity: analyzer.SeverityPass, Module: "purchase", 
		Message: "Goods Receipt converted to Supplier Invoice successfully",
	})

	// Step 6: Submit & Approve Supplier Invoice
	status, _, _ = s.client.Request(http.MethodPost, fmt.Sprintf("/purchase/supplier-invoices/%s/submit", siID), nil, RoleStaff)
	status, body, err = s.client.Request(http.MethodPost, fmt.Sprintf("/purchase/supplier-invoices/%s/approve", siID), nil, RoleManager)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-P06", Severity: analyzer.SeverityError, Module: "purchase", 
			Message: fmt.Sprintf("Failed to approve Supplier Invoice: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}

	findings = append(findings, analyzer.Finding{
		Code: "SIM-P06", Severity: analyzer.SeverityPass, Module: "purchase", 
		Message: "Supplier Invoice submitted & approved successfully. Journal created.",
	})

	// Optional Step 7: Purchase Payment (skipped for now due to Bank Account requirement)
	
	return findings
}
