package simulator

import (
	"fmt"
	"net/http"

	"github.com/gilabs/gims/api/analyzer"
)

func (s *SimulationChecker) runSalesFlow(cfg *analyzer.Config, runID string) []analyzer.Finding {
	findings := []analyzer.Finding{}
	
	// Pre-condition check: find a customer and a product
	_, getCustBody, err := s.client.Request(http.MethodGet, "/customer/customers?per_page=1", nil, RoleAdmin)
	if err != nil {
		findings = append(findings, analyzer.Finding{Code: "SIM-S01", Severity: analyzer.SeverityError, Module: "sales", Message: fmt.Sprintf("Failed to fetch customers: %v", err)})
		return findings
	}
	
	// Assume data structure follows typical REST list response map["data"][]interface{}
	data, ok := getCustBody["data"].([]interface{})
	if !ok || len(data) == 0 {
		findings = append(findings, analyzer.Finding{Code: "SIM-S01", Severity: analyzer.SeveritySkipped, Module: "sales", Message: "No customer found to run sales E2E flow"})
		return findings
	}
	customerID := data[0].(map[string]interface{})["id"].(string)

	_, getProdBody, err := s.client.Request(http.MethodGet, "/product/products?per_page=1", nil, RoleAdmin)
	if err != nil {
		return findings
	}
	prodData, ok := getProdBody["data"].([]interface{})
	if !ok || len(prodData) == 0 {
		findings = append(findings, analyzer.Finding{Code: "SIM-S01", Severity: analyzer.SeveritySkipped, Module: "sales", Message: "No products found to run sales E2E flow"})
		return findings
	}
	productID := prodData[0].(map[string]interface{})["id"].(string)
	
	// Pre-condition: fetch PaymentTerms, BusinessUnit, and SalesRep
	_, getPTBody, _ := s.client.Request(http.MethodGet, "/master-data/payment-terms?per_page=1", nil, RoleAdmin)
	ptData, _ := getPTBody["data"].([]interface{})
	paymentTermID := ptData[0].(map[string]interface{})["id"].(string)

	_, getBUBody, _ := s.client.Request(http.MethodGet, "/organization/business-units?per_page=1", nil, RoleAdmin)
	buData, _ := getBUBody["data"].([]interface{})
	businessUnitID := buData[0].(map[string]interface{})["id"].(string)

	_, getEmpBody, _ := s.client.Request(http.MethodGet, "/organization/employees?per_page=1", nil, RoleAdmin)
	empData, _ := getEmpBody["data"].([]interface{})
	salesRepID := empData[0].(map[string]interface{})["id"].(string)

	// Step 1: Create Sales Order
	soPayload := map[string]interface{}{
		"customer_id":      customerID,
		"order_date":       "2026-03-24",
		"payment_terms_id": paymentTermID,
		"business_unit_id": businessUnitID,
		"sales_rep_id":     salesRepID,
		"items": []map[string]interface{}{
			{
				"product_id": productID,
				"quantity":   1,
				"price":      100000,
			},
		},
		"notes": fmt.Sprintf("Auto-generated by QA Simulator %s", runID),
	}
	
	status, body, err := s.client.Request(http.MethodPost, "/sales/sales-orders", soPayload, RoleStaff)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-S01", 
			Severity: analyzer.SeverityError, 
			Module: "sales", 
			Message: fmt.Sprintf("Sales Order Creation Failed: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v, Err: %v", body, err),
		})
		return findings
	}
	
	findings = append(findings, analyzer.Finding{
		Code: "SIM-S01", 
		Severity: analyzer.SeverityPass, 
		Module: "sales", 
		Message: "Sales Order created successfully via API",
	})
	
	// Extract SO ID and Item ID
	soData, ok := body["data"].(map[string]interface{})
	if !ok {
		return findings
	}
	soID := soData["id"].(string)
	
	var soItemID string
	if items, ok := soData["items"].([]interface{}); ok && len(items) > 0 {
		soItemID = items[0].(map[string]interface{})["id"].(string)
	}

	// Step 1.5: Submit SO (required before approval)
	status, body, err = s.client.Request(http.MethodPatch, fmt.Sprintf("/sales/sales-orders/%s/status", soID), map[string]interface{}{"status": "submitted"}, RoleAdmin)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{Code: "SIM-S1.5", Severity: analyzer.SeverityError, Module: "sales", Message: fmt.Sprintf("Failed to submit SO: HTTP %d", status), Evidence: fmt.Sprintf("Body: %v", body)})
		return findings
	}
	findings = append(findings, analyzer.Finding{Code: "SIM-S1.5", Severity: analyzer.SeverityPass, Module: "sales", Message: "Sales Order submitted successfully"})

	// Step 2: Approve SO
	status, body, err = s.client.Request(http.MethodPost, fmt.Sprintf("/sales/sales-orders/%s/approve", soID), nil, RoleAdmin)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-S02", 
			Severity: analyzer.SeverityError, 
			Module: "sales", 
			Message: fmt.Sprintf("Failed to approve SO: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}

	findings = append(findings, analyzer.Finding{
		Code: "SIM-S02", 
		Severity: analyzer.SeverityPass, 
		Module: "sales", 
		Message: "Sales Order approved successfully by Admin via API",
	})

	// Step 3: Create Customer Invoice
	ciPayload := map[string]interface{}{
		"invoice_date":   "2026-03-24",
		"type":           "regular",
		"sales_order_id": soID,
		"notes":          "Auto-generated CI for QA Simulator",
		"items": []map[string]interface{}{
			{
				"product_id":          productID,
				"sales_order_item_id": soItemID,
				"quantity":            1,
				"price":               100000,
			},
		},
	}
	
	status, body, err = s.client.Request(http.MethodPost, "/sales/customer-invoices", ciPayload, RoleStaff)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-S03", 
			Severity: analyzer.SeverityError, 
			Module: "sales", 
			Message: fmt.Sprintf("Customer Invoice Creation Failed: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}

	findings = append(findings, analyzer.Finding{
		Code: "SIM-S03", 
		Severity: analyzer.SeverityPass, 
		Module: "sales", 
		Message: "Customer Invoice created successfully via API",
	})
	
	// Extract CI ID
	ciData, ok := body["data"].(map[string]interface{})
	if !ok {
		return findings
	}
	ciID := ciData["id"].(string)
	
	// Step 3.5: Submit Customer Invoice (required before approval)
	status, body, err = s.client.Request(http.MethodPatch, fmt.Sprintf("/sales/customer-invoices/%s/status", ciID), map[string]interface{}{"status": "submitted"}, RoleAdmin)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{Code: "SIM-S3.5", Severity: analyzer.SeverityError, Module: "sales", Message: fmt.Sprintf("Failed to submit Customer Invoice: HTTP %d", status), Evidence: fmt.Sprintf("Body: %v", body)})
		return findings
	}
	findings = append(findings, analyzer.Finding{Code: "SIM-S3.5", Severity: analyzer.SeverityPass, Module: "sales", Message: "Customer Invoice submitted successfully"})

	// Step 4: Approve Customer Invoice (This generates Accounts Receivable Journal automatically)
	status, body, err = s.client.Request(http.MethodPost, fmt.Sprintf("/sales/customer-invoices/%s/approve", ciID), nil, RoleAdmin)
	if err != nil || status >= 400 {
		findings = append(findings, analyzer.Finding{
			Code: "SIM-S04", 
			Severity: analyzer.SeverityError, 
			Module: "sales", 
			Message: fmt.Sprintf("Failed to approve Customer Invoice: HTTP %d", status),
			Evidence: fmt.Sprintf("Body: %v", body),
		})
		return findings
	}

	findings = append(findings, analyzer.Finding{
		Code: "SIM-S04", 
		Severity: analyzer.SeverityPass, 
		Module: "sales", 
		Message: "Customer Invoice approved successfully. AR Journal created automatically.",
	})
	
	return findings
}
