// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/gilabs/gims/api/internal/role/data/models"
	mock "github.com/stretchr/testify/mock"
)

// RoleRepository is an autogenerated mock type for the RoleRepository type
type RoleRepository struct {
	mock.Mock
}

// AssignPermissions provides a mock function with given fields: ctx, roleID, permissionIDs
func (_m *RoleRepository) AssignPermissions(ctx context.Context, roleID string, permissionIDs []string) error {
	ret := _m.Called(ctx, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountAdmins provides a mock function with given fields: ctx
func (_m *RoleRepository) CountAdmins(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountAdmins")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountUsersByRoleID provides a mock function with given fields: ctx, roleID
func (_m *RoleRepository) CountUsersByRoleID(ctx context.Context, roleID string) (int64, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for CountUsersByRoleID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, roleID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, ro
func (_m *RoleRepository) Create(ctx context.Context, ro *models.Role) error {
	ret := _m.Called(ctx, ro)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Role) error); ok {
		r0 = rf(ctx, ro)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *RoleRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *RoleRepository) FindByCode(ctx context.Context, code string) (*models.Role, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Role, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Role); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *RoleRepository) FindByID(ctx context.Context, id string) (*models.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissions provides a mock function with given fields: ctx, roleID
func (_m *RoleRepository) GetPermissions(ctx context.Context, roleID string) ([]string, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, page, limit, search
func (_m *RoleRepository) List(ctx context.Context, page int, limit int, search string) ([]models.Role, int64, error) {
	ret := _m.Called(ctx, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Role
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) ([]models.Role, int64, error)); ok {
		return rf(ctx, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) []models.Role); ok {
		r0 = rf(ctx, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) int64); ok {
		r1 = rf(ctx, page, limit, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string) error); ok {
		r2 = rf(ctx, page, limit, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, ro
func (_m *RoleRepository) Update(ctx context.Context, ro *models.Role) error {
	ret := _m.Called(ctx, ro)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Role) error); ok {
		r0 = rf(ctx, ro)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignPermissionsWithScope provides a mock function with given fields: ctx, roleID, assignments
func (_m *RoleRepository) AssignPermissionsWithScope(ctx context.Context, roleID string, assignments []models.RolePermission) error {
	ret := _m.Called(ctx, roleID, assignments)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissionsWithScope")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []models.RolePermission) error); ok {
		r0 = rf(ctx, roleID, assignments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoleRepository creates a new instance of RoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleRepository {
	mock := &RoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
