// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	tenantModels "github.com/gilabs/gims/api/internal/tenant/data/models"
	tenantRepositories "github.com/gilabs/gims/api/internal/tenant/data/repositories"
)

// TenantRepository is a mock type for the TenantRepository interface
type TenantRepository struct {
	mock.Mock
}

func (_m *TenantRepository) FindByID(ctx context.Context, id string) (*tenantModels.Tenant, error) {
	ret := _m.Called(ctx, id)

	var r0 *tenantModels.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*tenantModels.Tenant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *tenantModels.Tenant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenantModels.Tenant)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *TenantRepository) FindBySlug(ctx context.Context, slug string) (*tenantModels.Tenant, error) {
	ret := _m.Called(ctx, slug)
	var r0 *tenantModels.Tenant
	var r1 error
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*tenantModels.Tenant)
	}
	r1 = ret.Error(1)
	return r0, r1
}

func (_m *TenantRepository) FindAll(ctx context.Context) ([]tenantModels.Tenant, error) {
	ret := _m.Called(ctx)
	var r0 []tenantModels.Tenant
	var r1 error
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]tenantModels.Tenant)
	}
	r1 = ret.Error(1)
	return r0, r1
}

func (_m *TenantRepository) FindPaginated(ctx context.Context, search string, page, perPage int) ([]tenantModels.Tenant, int64, error) {
	ret := _m.Called(ctx, search, page, perPage)
	var r0 []tenantModels.Tenant
	var r1 int64
	var r2 error
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]tenantModels.Tenant)
	}
	r1 = ret.Get(1).(int64)
	r2 = ret.Error(2)
	return r0, r1, r2
}

func (_m *TenantRepository) FindPaginatedWithCounts(ctx context.Context, search string, page, perPage int) ([]tenantRepositories.TenantWithCounts, int64, error) {
	ret := _m.Called(ctx, search, page, perPage)
	var r0 []tenantRepositories.TenantWithCounts
	var r1 int64
	var r2 error
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]tenantRepositories.TenantWithCounts)
	}
	r1 = ret.Get(1).(int64)
	r2 = ret.Error(2)
	return r0, r1, r2
}

func (_m *TenantRepository) FindByIDWithCounts(ctx context.Context, id string) (*tenantRepositories.TenantWithCounts, error) {
	ret := _m.Called(ctx, id)
	var r0 *tenantRepositories.TenantWithCounts
	var r1 error
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*tenantRepositories.TenantWithCounts)
	}
	r1 = ret.Error(1)
	return r0, r1
}

func (_m *TenantRepository) CountActiveUsers(ctx context.Context, tenantID string) (int64, error) {
	ret := _m.Called(ctx, tenantID)
	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *TenantRepository) Create(ctx context.Context, tenant *tenantModels.Tenant) error {
	ret := _m.Called(ctx, tenant)
	return ret.Error(0)
}

func (_m *TenantRepository) Update(ctx context.Context, tenant *tenantModels.Tenant) error {
	ret := _m.Called(ctx, tenant)
	return ret.Error(0)
}

// NewTenantRepository creates a new instance of TenantRepository.
func NewTenantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantRepository {
	m := &TenantRepository{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

// Ensure TenantRepository implements the interface at compile time.
var _ tenantRepositories.TenantRepository = (*TenantRepository)(nil)
