package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/gilabs/gims/api/analyzer"
	"github.com/gilabs/gims/api/analyzer/reporter"
	"github.com/gilabs/gims/api/analyzer/scanner"
	"github.com/gilabs/gims/api/analyzer/simulator"
	"github.com/gilabs/gims/api/analyzer/validator"
	"github.com/gilabs/gims/api/internal/core/infrastructure/config"
	"github.com/gilabs/gims/api/internal/core/infrastructure/database"
	"github.com/gilabs/gims/api/internal/core/logger"
)

func main() {
	// Parse CLI flags
	var modulesFlag string
	var fromDateFlag string
	var toDateFlag string
	var strictFlag bool
	var outputsFlag string
	var outputDirFlag string
	var dryRunFlag bool
	var modeFlag string
	var scenarioFlag string
	var cleanupFlag bool
	var failOnSkippedMandatoryFlag bool

	flag.StringVar(&modulesFlag, "module", "", "Comma-separated list of modules to analyze (e.g., 'finance,sales,purchase')")
	flag.StringVar(&fromDateFlag, "from-date", "", "Start date for financial checks (YYYY-MM-DD), default is 1st day of current month")
	flag.StringVar(&toDateFlag, "to-date", "", "End date for financial checks (YYYY-MM-DD), default is today")
	flag.BoolVar(&strictFlag, "strict", false, "Promote warnings to errors")
	flag.StringVar(&outputsFlag, "output", "console", "Comma-separated list of output formats (console, json, txt)")
	flag.StringVar(&outputDirFlag, "output-dir", "./reports", "Directory for file reports")
	flag.BoolVar(&dryRunFlag, "dry-run", false, "Print checkers that would be run without actually running them")
	flag.StringVar(&modeFlag, "mode", "full", "Analysis mode: validate, simulation, full")
	flag.StringVar(&scenarioFlag, "scenario", "", "Scenario filter for simulation (e.g. FIN-SIM-JE-01)")
	flag.BoolVar(&cleanupFlag, "cleanup", true, "Auto-cleanup test data generated by simulator")
	flag.BoolVar(&failOnSkippedMandatoryFlag, "fail-on-skipped-mandatory", false, "Fail if any mandatory scenario is skipped")
	flag.Parse()

	cfg := analyzer.DefaultConfig()

	// 1. Process Modules
	if modulesFlag != "" {
		cfg.Modules = strings.Split(modulesFlag, ",")
		for i, m := range cfg.Modules {
			cfg.Modules[i] = strings.TrimSpace(m)
		}
	}

	// 2. Process Dates
	if fromDateFlag != "" {
		if t, err := time.Parse("2006-01-02", fromDateFlag); err == nil {
			cfg.FromDate = t
		} else {
			log.Fatalf("Invalid from-date format. Use YYYY-MM-DD")
		}
	}
	if toDateFlag != "" {
		if t, err := time.Parse("2006-01-02", toDateFlag); err == nil {
			cfg.ToDate = t
		} else {
			log.Fatalf("Invalid to-date format. Use YYYY-MM-DD")
		}
	}

	// 3. Process outputs & modes
	cfg.OutputFormats = strings.Split(outputsFlag, ",")
	for i, o := range cfg.OutputFormats {
		cfg.OutputFormats[i] = strings.TrimSpace(strings.ToLower(o))
	}
	cfg.OutputDir = outputDirFlag
	cfg.Strict = strictFlag
	cfg.DryRun = dryRunFlag
	cfg.Mode = modeFlag
	cfg.Scenario = scenarioFlag
	cfg.Cleanup = cleanupFlag
	cfg.FailOnSkippedMandatory = failOnSkippedMandatoryFlag

	// Load App Context (not needed for dry-run)
	if !cfg.DryRun {
		logger.Init()
		if err := config.Load(); err != nil {
			log.Fatalf("Failed to load config: %v", err)
		}
		if err := database.Connect(); err != nil {
			log.Fatalf("Failed to connect to db: %v", err)
		}
		defer database.Close()
	}

	engine := analyzer.NewEngine()

	// Register Scanners & Validators
	engine.RegisterChecker(scanner.NewRBACScanner())
	engine.RegisterChecker(validator.NewFinanceValidator())
	engine.RegisterChecker(validator.NewJournalValidator())
	engine.RegisterChecker(validator.NewFlowValidator())
	engine.RegisterChecker(validator.NewIntegrityValidator())
	engine.RegisterChecker(validator.NewClosingValidator())
	engine.RegisterChecker(simulator.NewSimulationChecker())

	// Register Reporters based on config
	for _, outFormat := range cfg.OutputFormats {
		switch outFormat {
		case "console":
			engine.RegisterReporter(reporter.NewConsoleReporter())
		case "json":
			engine.RegisterReporter(reporter.NewJSONReporter())
		case "txt", "text":
			engine.RegisterReporter(reporter.NewTextReporter())
		default:
			log.Printf("Unknown output format '%s', skipping", outFormat)
		}
	}

	if err := engine.Run(cfg); err != nil {
		fmt.Printf("\n❌ Analyzer failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("\n✅ Analysis complete without critical errors.")
}
