package dto

import geographic "github.com/gilabs/gims/api/internal/geographic/domain/dto"

// CreateWarehouseRequest represents the request to create a warehouse.
// Code is auto-generated by the backend (WH-XXXXX format) and must not be submitted.
type CreateWarehouseRequest struct {
	Name        string   `json:"name" validate:"required,min=2,max=200"`
	Description string   `json:"description,omitempty"`
	Address     string   `json:"address,omitempty"`
	ProvinceID  *string  `json:"province_id,omitempty"`
	CityID      *string  `json:"city_id,omitempty"`
	DistrictID  *string  `json:"district_id,omitempty"`
	VillageID   *string  `json:"village_id,omitempty"`
	VillageName *string  `json:"village_name,omitempty"`
	Latitude    *float64 `json:"latitude,omitempty"`
	Longitude   *float64 `json:"longitude,omitempty"`
	IsPosOutlet *bool    `json:"is_pos_outlet,omitempty"`
	OutletID    *string  `json:"outlet_id,omitempty"`
	IsActive    *bool    `json:"is_active,omitempty"`
}

// UpdateWarehouseRequest represents the request to update a warehouse
type UpdateWarehouseRequest struct {
	Code        *string  `json:"code,omitempty" validate:"omitempty,min=2,max=50"`
	Name        *string  `json:"name,omitempty" validate:"omitempty,min=2,max=200"`
	Description *string  `json:"description,omitempty"`
	Address     *string  `json:"address,omitempty"`
	ProvinceID  *string  `json:"province_id,omitempty"`
	CityID      *string  `json:"city_id,omitempty"`
	DistrictID  *string  `json:"district_id,omitempty"`
	VillageID   *string  `json:"village_id,omitempty"`
	VillageName *string  `json:"village_name,omitempty"`
	Latitude    *float64 `json:"latitude,omitempty"`
	Longitude   *float64 `json:"longitude,omitempty"`
	IsPosOutlet *bool    `json:"is_pos_outlet,omitempty"`
	OutletID    *string  `json:"outlet_id,omitempty"`
	IsActive    *bool    `json:"is_active,omitempty"`
}

// WarehouseResponse represents the warehouse response
type WarehouseResponse struct {
	ID          string                  `json:"id"`
	Code        string                  `json:"code"`
	Name        string                  `json:"name"`
	Description string                  `json:"description,omitempty"`
	Address     string                  `json:"address,omitempty"`
	ProvinceID  *string                 `json:"province_id,omitempty"`
	Province    *geographic.ProvinceResponse `json:"province,omitempty"`
	CityID      *string                 `json:"city_id,omitempty"`
	City        *geographic.CityResponse     `json:"city,omitempty"`
	DistrictID  *string                 `json:"district_id,omitempty"`
	District    *geographic.DistrictResponse `json:"district,omitempty"`
	VillageID   *string                 `json:"village_id,omitempty"`
	VillageName *string                 `json:"village_name,omitempty"`
	Village     *geographic.VillageResponse  `json:"village,omitempty"`
	Latitude    *float64                `json:"latitude,omitempty"`
	Longitude   *float64                `json:"longitude,omitempty"`
	IsPosOutlet bool                    `json:"is_pos_outlet"`
	OutletID    *string                 `json:"outlet_id,omitempty"`
	IsActive    bool                    `json:"is_active"`
	HasStock    bool                    `json:"has_stock"`
	CreatedAt   string                  `json:"created_at"`
	UpdatedAt   string                  `json:"updated_at"`
}
